# Generated by Django 2.1.1 on 2019-08-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ticket_get',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='ticket_used',
            field=models.BooleanField(default=False),
        ),
    ]
