# Generated by Django 2.1.1 on 2019-08-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190823_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ticket_get',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ticket_used',
        ),
    ]
