# Generated by Django 2.1.1 on 2019-08-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='coupon_get',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='coupon_used',
            field=models.BooleanField(default=False),
        ),
    ]
