# Generated by Django 2.1.1 on 2019-08-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20190823_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='coupon_get',
        ),
        migrations.RemoveField(
            model_name='video',
            name='coupon_used',
        ),
        migrations.AddField(
            model_name='videouser',
            name='coupon_get',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videouser',
            name='coupon_used',
            field=models.BooleanField(default=False),
        ),
    ]
